# Generated by Django 5.2.14 on 2026-05-05 17:00

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.BigAutoField(db_column='badge_id', primary_key=True, serialize=False, verbose_name='identifiant badge')),
                ('badge_name', models.CharField(db_column='badge_name', max_length=200, verbose_name='nom')),
                ('icon_url', models.URLField(db_column='icon_url', max_length=500, verbose_name='URL de l’icône')),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'db_table': 'badge',
                'ordering': ['badge_name'],
            },
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('cosmetic_id', models.BigAutoField(db_column='cosmetic_id', primary_key=True, serialize=False, verbose_name='identifiant cosmétique')),
                ('cosmetic_name', models.CharField(db_column='cosmetic_name', max_length=200, verbose_name='nom')),
                ('cosmetic_category', models.CharField(db_column='cosmetic_category', help_text='À normaliser via les serializers / catalogue métier.', max_length=64, verbose_name='catégorie')),
                ('cosmetic_cost', models.PositiveIntegerField(db_column='cosmetic_cost', verbose_name='coût')),
                ('cosmetic_asset_url', models.URLField(db_column='cosmetic_asset_url', max_length=500, verbose_name='URL de l’asset')),
            ],
            options={
                'verbose_name': 'cosmétique',
                'verbose_name_plural': 'cosmétiques',
                'db_table': 'cosmetic',
                'ordering': ['cosmetic_category', 'cosmetic_name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(db_column='question_id', primary_key=True, serialize=False, verbose_name='identifiant question')),
                ('question_content', models.TextField(db_column='question_content', verbose_name='énoncé')),
                ('xp_value', models.PositiveIntegerField(db_column='xp_value', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valeur XP')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'question',
                'ordering': ['quiz', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.BigAutoField(db_column='rank_id', primary_key=True, serialize=False, verbose_name='identifiant rang')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('xp_threshold', models.PositiveBigIntegerField(db_column='xp_threshold', default=0, help_text='XP minimum pour atteindre ce rang (inclus).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='seuil XP')),
                ('stars', models.PositiveSmallIntegerField(db_column='stars', default=1, help_text='1 = débutant, 2 = confirmé, 3 = expert.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='étoiles')),
            ],
            options={
                'verbose_name': 'rang',
                'verbose_name_plural': 'rangs',
                'db_table': 'rank',
                'ordering': ['xp_threshold'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(db_column='role_id', primary_key=True, serialize=False, verbose_name='identifiant rôle')),
                ('role_name', models.CharField(db_column='role_name', max_length=150, unique=True, verbose_name='nom du rôle')),
                ('role_rights', models.JSONField(default=dict, help_text='Structure JSON des permissions (ne jamais faire confiance au seul client).', verbose_name='droits')),
            ],
            options={
                'verbose_name': 'rôle',
                'verbose_name_plural': 'rôles',
                'db_table': 'role',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.BigAutoField(db_column='theme_id', primary_key=True, serialize=False, verbose_name='identifiant thème')),
                ('theme_title', models.CharField(db_column='theme_title', max_length=255, verbose_name='titre')),
            ],
            options={
                'verbose_name': 'thème',
                'verbose_name_plural': 'thèmes',
                'db_table': 'theme',
                'ordering': ['theme_title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(editable=False, help_text='Aligné sur l’e-mail pour la compatibilité Django.', max_length=150, unique=True, verbose_name='pseudo interne')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('formateur', models.ForeignKey(blank=True, db_column='formateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenants', to=settings.AUTH_USER_MODEL, verbose_name='formateur référent')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(db_column='course_id', primary_key=True, serialize=False, verbose_name='identifiant cours')),
                ('course_title', models.CharField(db_column='course_title', max_length=255, verbose_name='titre')),
                ('body_content', models.TextField(db_column='body_content', verbose_name='contenu')),
                ('map_order', models.PositiveIntegerField(db_column='map_order', default=0, verbose_name='ordre sur la carte')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('delivered_badge', models.OneToOneField(blank=True, db_column='delivered_badge_id', help_text='Relation MCD : DELIVRER (un cours → un badge ; un badge → au plus un cours).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_delivery', to='edunova.badge', verbose_name='badge délivré')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'db_table': 'course',
                'ordering': ['theme', 'map_order', 'course_title'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('enrollment_id', models.BigAutoField(db_column='enrollment_id', primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrit le')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='edunova.course')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscription cours',
                'verbose_name_plural': 'inscriptions cours',
                'db_table': 'course_enrollment',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='courses_followed',
            field=models.ManyToManyField(blank=True, related_name='followers', through='edunova.CourseEnrollment', to='edunova.course'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.BigAutoField(db_column='answer_id', primary_key=True, serialize=False, verbose_name='identifiant réponse')),
                ('label_answer', models.TextField(db_column='label_answer', verbose_name='libellé')),
                ('is_correct', models.BooleanField(db_column='is_correct', default=False, verbose_name='réponse correcte')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='edunova.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'réponse',
                'verbose_name_plural': 'réponses',
                'db_table': 'answer',
                'ordering': ['question', 'answer_id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.BigAutoField(db_column='quiz_id', primary_key=True, serialize=False, verbose_name='identifiant quiz')),
                ('coins_on_success', models.PositiveIntegerField(db_column='coins_on_success', verbose_name='pièces si réussite')),
                ('min_score_to_pass', models.PositiveSmallIntegerField(db_column='min_score_to_pass', help_text='Pourcentage entier entre 0 et 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score minimum pour valider')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quiz',
                'db_table': 'quiz',
                'ordering': ['quiz_id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edunova.quiz', verbose_name='quiz'),
        ),
        migrations.AddField(
            model_name='course',
            name='validating_quiz',
            field=models.ForeignKey(db_column='validating_quiz_id', help_text='Relation MCD\u202f: VALIDER.', on_delete=django.db.models.deletion.PROTECT, related_name='validated_courses', to='edunova.quiz', verbose_name='quiz de validation'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(db_column='profile_id', primary_key=True, serialize=False, verbose_name='identifiant profil')),
                ('total_xp', models.PositiveBigIntegerField(db_column='total_xp', default=0, verbose_name='XP total')),
                ('wallet_balance', models.PositiveBigIntegerField(db_column='wallet_balance', default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='solde portefeuille')),
                ('current_avatar_url', models.URLField(blank=True, db_column='current_avatar_url', default='', max_length=500, verbose_name='URL avatar actuel')),
                ('current_banner_url', models.URLField(blank=True, db_column='current_banner_url', default='', max_length=500, verbose_name='URL bannière actuelle')),
                ('current_streak', models.PositiveIntegerField(db_column='current_streak', default=0, verbose_name='série courante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('rank', models.ForeignKey(blank=True, db_column='rank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='edunova.rank', verbose_name='rang')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
                'db_table': 'profile',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='edunova.role', verbose_name='rôle'),
        ),
        migrations.AddField(
            model_name='course',
            name='theme',
            field=models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='edunova.theme', verbose_name='thème'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('user_badge_id', models.BigAutoField(db_column='user_badge_id', primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='obtenu le')),
                ('badge', models.ForeignKey(db_column='badge_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='edunova.badge')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='badge_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'badge utilisateur',
                'verbose_name_plural': 'badges utilisateurs',
                'db_table': 'user_badge',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='badges_earned',
            field=models.ManyToManyField(blank=True, related_name='earned_by_users', through='edunova.UserBadge', to='edunova.badge'),
        ),
        migrations.CreateModel(
            name='UserCosmeticPurchase',
            fields=[
                ('purchase_id', models.BigAutoField(db_column='purchase_id', primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='acheté le')),
                ('cosmetic', models.ForeignKey(db_column='cosmetic_id', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='edunova.cosmetic')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='cosmetic_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'achat cosmétique',
                'verbose_name_plural': 'achats cosmétiques',
                'db_table': 'user_cosmetic_purchase',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='cosmetics_purchased',
            field=models.ManyToManyField(blank=True, related_name='buyers', through='edunova.UserCosmeticPurchase', to='edunova.cosmetic'),
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('progress_id', models.BigAutoField(db_column='progress_id', primary_key=True, serialize=False)),
                ('is_unlocked', models.BooleanField(db_column='is_unlocked', default=False, verbose_name='débloqué')),
                ('is_completed', models.BooleanField(db_column='is_completed', default=False, verbose_name='complété')),
                ('best_score', models.PositiveSmallIntegerField(db_column='best_score', default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='meilleur score')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='débloqué le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='complété le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='edunova.course')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progression cours utilisateur',
                'verbose_name_plural': 'progressions cours utilisateur',
                'db_table': 'user_course_progress',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.BigAutoField(db_column='log_id', primary_key=True, serialize=False, verbose_name='identifiant log')),
                ('action', models.CharField(choices=[('register', 'inscription'), ('login', 'connexion'), ('logout', 'déconnexion'), ('quiz_submit', 'soumission quiz'), ('course_enroll', 'inscription cours'), ('course_unenroll', 'désinscription cours'), ('cosmetic_purchase', 'achat cosmétique'), ('course_create', 'création cours'), ('course_update', 'modification cours'), ('course_delete', 'suppression cours'), ('quiz_create', 'création quiz'), ('quiz_update', 'modification quiz'), ('quiz_delete', 'suppression quiz'), ('question_create', 'création question'), ('question_update', 'modification question'), ('question_delete', 'suppression question'), ('answer_create', 'création réponse'), ('answer_update', 'modification réponse'), ('answer_delete', 'suppression réponse')], db_column='action', max_length=40, verbose_name='action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexte libre : score, ids liés, résultat, etc.', verbose_name='métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='ip_address', null=True, verbose_name='adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "log d'activité",
                'verbose_name_plural': "logs d'activité",
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_log_user_date'), models.Index(fields=['action'], name='idx_log_action')],
            },
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_user_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='uniq_user_badge'),
        ),
        migrations.AddConstraint(
            model_name='usercosmeticpurchase',
            constraint=models.UniqueConstraint(fields=('user', 'cosmetic'), name='uniq_user_cosmetic_purchase'),
        ),
        migrations.AddConstraint(
            model_name='usercourseprogress',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_user_course_progress'),
        ),
    ]
