# Generated by Django 5.2.14 on 2026-05-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', 'inscription'), ('login', 'connexion'), ('logout', 'déconnexion'), ('quiz_submit', 'soumission quiz'), ('course_enroll', 'inscription cours'), ('course_unenroll', 'désinscription cours'), ('cosmetic_purchase', 'achat cosmétique'), ('course_create', 'création cours'), ('course_update', 'modification cours'), ('course_delete', 'suppression cours'), ('quiz_create', 'création quiz'), ('quiz_update', 'modification quiz'), ('quiz_delete', 'suppression quiz'), ('question_create', 'création question'), ('question_update', 'modification question'), ('question_delete', 'suppression question'), ('answer_create', 'création réponse'), ('answer_update', 'modification réponse'), ('answer_delete', 'suppression réponse'), ('ai_course_generate', 'génération IA d’un cours')], db_column='action', max_length=40, verbose_name='action'),
        ),
    ]
