# Generated by Django 5.2.13 on 2026-05-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='delivered_badge',
            field=models.OneToOneField(db_column='delivered_badge_id', help_text='Relation MCD\u202f: DELIVRER (un cours → un badge ; un badge → au plus un cours).', on_delete=django.db.models.deletion.PROTECT, related_name='course_delivery', to='edunova.badge', verbose_name='badge délivré'),
        ),
        migrations.AlterField(
            model_name='course',
            name='validating_quiz',
            field=models.ForeignKey(db_column='validating_quiz_id', help_text='Relation MCD\u202f: VALIDER.', on_delete=django.db.models.deletion.PROTECT, related_name='validated_courses', to='edunova.quiz', verbose_name='quiz de validation'),
        ),
    ]
