# Generated by Django 5.2.13 on 2026-05-05 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunova', '0003_usercourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AlterField(
            model_name='course',
            name='delivered_badge',
            field=models.OneToOneField(blank=True, db_column='delivered_badge_id', help_text='Relation MCD : DELIVRER (un cours → un badge ; un badge → au plus un cours).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_delivery', to='edunova.badge', verbose_name='badge délivré'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.BigAutoField(db_column='log_id', primary_key=True, serialize=False, verbose_name='identifiant log')),
                ('action', models.CharField(choices=[('register', 'inscription'), ('login', 'connexion'), ('logout', 'déconnexion'), ('quiz_submit', 'soumission quiz'), ('course_enroll', 'inscription cours'), ('course_unenroll', 'désinscription cours'), ('cosmetic_purchase', 'achat cosmétique'), ('course_create', 'création cours'), ('course_update', 'modification cours'), ('course_delete', 'suppression cours'), ('quiz_create', 'création quiz'), ('quiz_update', 'modification quiz'), ('quiz_delete', 'suppression quiz'), ('question_create', 'création question'), ('question_update', 'modification question'), ('question_delete', 'suppression question'), ('answer_create', 'création réponse'), ('answer_update', 'modification réponse'), ('answer_delete', 'suppression réponse')], db_column='action', max_length=40, verbose_name='action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexte libre : score, ids liés, résultat, etc.', verbose_name='métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='ip_address', null=True, verbose_name='adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "log d'activité",
                'verbose_name_plural': "logs d'activité",
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_log_user_date'), models.Index(fields=['action'], name='idx_log_action')],
            },
        ),
    ]
