# Generated by Django 5.2.13 on 2026-05-05 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunova', '0004_course_created_by_quiz_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='formateur',
            field=models.ForeignKey(blank=True, db_column='formateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenants', to=settings.AUTH_USER_MODEL, verbose_name='formateur référent'),
        ),
    ]
