# Generated by Django 5.2.13 on 2026-05-05 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunova', '0005_user_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='stars',
            field=models.PositiveSmallIntegerField(db_column='stars', default=1, help_text='1 = débutant, 2 = confirmé, 3 = expert.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='étoiles'),
        ),
    ]
